### ISSUE TITLE
No Data From AquaRite Chlorinator.

### ISSUE THREAD

**Issue by 556duckvader** [tagyoureit/nodejs-poolController#293]
I have my AquaRite SWG connected with a USB RS485 dongle and it doesn’t appear to be receiving any data from the SWG. Photos of how I have it connected and all the packet captures are attached.  

**Pool Equipment**
 - Controller: None I have it setup as a Virtual Controller as I only have the AquaRite SWG
 - Chlorinator: Hayward Aqua-Rite T-15

**Desktop (please complete the following information):**
 - OS: Windows 10 and  Mac IOS
 - Browser: Chrome
 - Version: 90.0.4430.93

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: iOS 14.5.1
 - Browser Chrome
 - Version

![IMG_0371](https://user-images.githubusercontent.com/17590678/117750476-77c3a300-b1e1-11eb-9699-baf3689c3fdb.JPG)
![IMG_0369](https://user-images.githubusercontent.com/17590678/117750481-798d6680-b1e1-11eb-8dcf-4bf0cfa03802.JPG)
[Aqua-Rite-SWG-Issues.zip](https://github.com/tagyoureit/nodejs-poolController/files/6456245/Aqua-Rite-SWG-Issues.zip)

**Comment by rstrouse** [comment]
I looked at your output and it appears the adapter is not responding.  njsPC is sending out the proper requests in the proper format for the SWG but there is no response from the SWG.

Your wiring **looks** correct however, this wouldn't be the first time that we have seen the adapter + / - mislabeled (no kidding).  You can try to switch these and see if the adapter starts responding.

If that doesn't work, we have recently experienced a large number of JBTek adapters that failed or never worked.  We have removed this from our recommended adapter list and have gotten feedback from our users for adapters that work better than the JBTek adapters.

**Comment by 556duckvader** [comment]
I will swap the cables and see what happens.  I also have another adapter being delivered tomorrow so I will try that one too.

**Comment by 556duckvader** [comment]
I reversed the wires on the dongle and its didn't come up so now I am waiting on my new dongle to get delivered today.

**Comment by 556duckvader** [comment]
I have tried 3 different RS485 adapters and I can't seem to get any of them to work so either I am doing something really wrong or my RS485 port on my Aquarite is not working.

**Comment by rstrouse** [comment]
I assume you have seen this.  It appears someone with an AquaRite chimed in and you do need to power the Aquarite controller.
https://gitter.im/nodejs-poolController/Lobby?at=60a35290c12aec4aa2d0714e

**Comment by colin-young** [comment]
@556duckvader do you have read/write access to the adapter? That's not a given by default. I ran into this problem with my pump and I haven't seen it documented anywhere.

`chmod o+rw /dev/ttyUSB0` (or whatever your adapter is) got it sorted for me. I started with the JBTek then ordered the industrial adapter when that wasn't working, then discovered [this answer](https://unix.stackexchange.com/a/117064) on Stackexchange Unix & Linux.

It seems obvious in retrospect.

**Comment by 556duckvader** [comment]
I got a new RS485 dongle and supplied the Aquarite 12v and it’s working now.

**Comment by psmith3** [comment]
> I got a new RS485 dongle and supplied the Aquarite 12v and it’s working now.

I am having the same set of issues you had and have both the JBTek and now the industrial RS485 adapter. I have a 12 V power supply with 300 mA output connected to the ground and 10 V input on the Aquarite board. I assume 12 V is OK, but do I have enough amperage? how many amps does your 12 V power adapter put out? I have tried every which way under the sun to get data via Windows laptop and Raspberry PI with no luck. I have swapped the data leads and still get nothing. Does the ground on the industrial RS485 adapter need to be connected to the ground in the Aquarite? Like you, I have no other controller device connected and only the adapter.

**Comment by 556duckvader** [comment]
My 12v adapter is like 2amps.  I did connect the ground to the power supply as well as my RS485 adapter had a ground connection too.
![Uploading 6A0FC750-4D81-423D-AC9A-49A80CCE4D65.jpeg…]()

**Comment by psmith3** [comment]
Pulling my hair out and still cannot get to put out any data. I changed my 12vdc power adapter to one that outputs 2amps like yours. Still no output. Is there anything else that could prevent the Aquarite RS485 port from working? I do recall once, initially with the JBTek adapter on my windows laptop, I did get an output and did not have power connected to the Aquarite. It was not the output from the guide and I never saw it again. Is there any chance of shorting something out on the RS485 connector? Here are pictures of my connections. 
![0E81D643-D0C9-4FDB-B673-E1DEC8819157](https://user-images.githubusercontent.com/14373163/120378512-268c6800-c2e4-11eb-9a32-c9fecd223254.jpeg)
![CF56BED1-C00B-4479-9D6F-428252D981D6](https://user-images.githubusercontent.com/14373163/120378513-27bd9500-c2e4-11eb-9362-892187c8adcc.jpeg)
![291BF288-8532-4FC2-A5E6-63E83AB17D90](https://user-images.githubusercontent.com/14373163/120378517-27bd9500-c2e4-11eb-9caf-2d5d25a0f17e.jpeg)

**Comment by 556duckvader** [comment]
One thing I did was delete the poolConfig.json  and poolState.json file from the data directory in the nodes-poolController directory.  Did a fresh npm start and let it discover it.

**Comment by psmith3** [comment]
> One thing I did was delete the poolConfig.json and poolState.json file from the data directory in the nodes-poolController directory. Did a fresh npm start and let it discover it.

I am trying that now, but I am more concerned over not being able to see data with a Windows Laptop running RealTerm app. I now have it hooked back up to my Raspberry PI and am not seeing data using the  od -x < /dev/ttyUSB0. Did you get anything using those methods?

**Comment by 556duckvader** [comment]
Nope.  I did make sure the USB was able to be written to with chmod o+rw /dev/ttyUSB0

**Comment by psmith3** [comment]
> Nope. I did make sure the USB was able to be written to with chmod o+rw /dev/ttyUSB0

ok. Thanks. I did that as well. Did you have to set any of the values for the ttyUSB0, like Speed, flow control, etc?

**Comment by 556duckvader** [comment]
I only set those setting in the config.json.

**Comment by tagyoureit** [comment]
> I now have it hooked back up to my Raspberry PI and am not seeing data using the od -x < /dev/ttyUSB0. Did you get anything using those methods?

Most ancillary products won't be chatty unless they are specifically initialized. You won't see the chlorinator sending random packets via this method. 

Since you now have two adapters, you could connect one to the other as a loopback device. Hook up one to njsPC and use the 'od -x ...' command on it. That could let you see if your outbound packets are being sent correctly.

**Comment by magimat** [comment]
@psmith3  did you ever get this to work?  cause I have a feeling I have the exact same trouble.

I too have an Aquarite SGW that I'm trying to connect to directly from nodejs-poolcontroller using a rs485 dongle on a rpi.

I doubled checked wiring (yellow from SWG to b- and black from SWG to a+) and I also supply 10v to the connector on the SWG. It says 10v so I use a 12v wall wart and a buck converter to get it down to 10v, but maybe I just need to keep it at 12v ?

Dongle is detected as ttyUSB0 and Everything looks fine, but when I try the od -x command on the pi, I get nothing and of course nodejs-poolController doesnt seem to communicate neiher so I'm scratching my head here and was wondering if you ever solved this, because it sounds pretty similar to my problem.

thanks!

**Comment by magimat** [comment]
ok, i'm happy to report it now works. Turns out my problem was running the software using docker. When I started poolController directly from the commandline using npm start, it all started to work.

So, it means somehow, docker can't access my usb dongle. I tried about eveything I know, --privileged, --group-add dialout, even -v /dev:/dev but nothing seems to works inside docker .... sad because I really wanted this to work inside a container and I did access some usb devices from docker on the pi before, so it must be possible

Anyway idea about that??

**Comment by magimat** [comment]
one more update if anyone reads this in the future,  I finally have it working inside docker!!

I resorted to build my own docker image natively on the raspberry pi, simply using a fresh clone of the repo, but apparently, building the image directly on the pi did have some effect, because now it work!

So there is still some docker magic that I can't explain, but now it works, so I'm a happy camper :)

**Comment by psmith3** [comment]
> one more update if anyone reads this in the future, I finally have it working inside docker!!
> 
> I resorted to build my own docker image natively on the raspberry pi, simply using a fresh clone of the repo, but apparently, building the image directly on the pi did have some effect, because now it work!
> 
> So there is still some docker magic that I can't explain, but now it works, so I'm a happy camper :)

Glad you got it working. Just saw your question. Sorry I did not see it earlier.
