### ISSUE TITLE
NJSPC Not Working with Standalone Pump

### ISSUE THREAD

**Issue by Exit2Studios** [tagyoureit/nodejs-poolController#313]
**Describe the bug**
Unable to get NJSPC working after lightning strike nearby stopped it working.  Updated to v7.1 and getting the following errors.

**To Reproduce**
npm start

**Expected behavior**
Get current speeds of pump and be able to control it via mqtt from home assistant

**Screenshots**
N/A

**Packet Capture**
attached
[replay.zip](https://github.com/tagyoureit/nodejs-poolController/files/6601554/replay.zip)

**Pool Equipment**
 - Controller: N/A (Hayward not used to control pump)
 - Controller Model: N/A
 - Controller Firmware Version: N/A
 - Pump(s) manufacturer and model: IntelliFlow VSF
 - Chlorinator: 
 - Heater(s): 
 - Chemical controller: 
 - Valves: 
 - Any other relevant equipment:

**Desktop (please complete the following information):**
 - OS: Raspberry Pi
 - Browser Firefox and Safari
 - Version 
 - 

**Smartphone (please complete the following information):**
N/A (iPhone)

**Additional context**

**Comment by tagyoureit** [comment]
Per Gitter  :point_up: [June 4, 2021 12:59 PM](https://gitter.im/nodejs-poolController/Lobby?at=60ba863abbcdca5603e56b6d):

> I'm getting the following:Error sending setDriveState for Pump 1 : Message aborted after 2 attempt(s): 165,0,96,33,6,1,4,1,49
[6/4/2021, 5:12:51 PM] error: Error running pump sequence for Pump 1: Message aborted after 2 attempt(s): 165,0,96,33,6,1,4,1,49
[6/4/2021, 5:12:51 PM] error: N


I am only seeing outbound packets in your logs:
`{"id":98,"valid":true,"dir":"out","proto":"pump","pkt":[[],[255,0,255],[165,0,96,33,6,1],[4],[1,49]],"ts":"2021-06-04T17:43:00.985-0500"}`
The pump isn't responding with an error or anything for that matter.  We correctly state the message is aborted because there is no response to it.

You may want to check your wiring, or like you originally suggested, maybe the adapter went bad?

**Comment by tagyoureit** [comment]
Did you have success here?

**Comment by Exit2Studios** [comment]
I just got a new adapter and everything is working now. That is the second adapter I’ve lost right after a power outage. I need to look into some type of surge protection or UPS.
