### ISSUE TITLE
Issue with Circuit Groups

### ISSUE THREAD

**Issue by Exit2Studios** [tagyoureit/nodejs-poolController#361]
**Describe the bug**
Getting strange behavior when turning on a circuit group.  It turns on others.

**To Reproduce**
1. Go to features
2. Click on Spa Spill G
3. Waterfall G turns on

**Expected behavior**
Only selected group turns on

**Screenshots**
![Capture](https://user-images.githubusercontent.com/16908875/138955758-e4ebcc08-c8eb-4ec2-a9e4-bcbfe9b0ea5f.gif)

<img width="635" alt="image" src="https://user-images.githubusercontent.com/16908875/138956049-1a4592f2-d06d-4a54-85b6-d889440b6ee1.png">

**Config Files**
[Archive.zip](https://github.com/tagyoureit/nodejs-poolController/files/7422097/Archive.zip)

**Pool Equipment**
 - Controller: N/A
 - Controller Model: N/A
 - Controller Firmware N/A
 - Pump(s) manufacturer and model: IntelliFlow VSF
 - Chlorinator: Roll your own (Stenner)
 - Heater(s): Gas
 - Chemical controller: Relay Equipment Manager (REM)
 - Valves: 24vac actuators
 - Any other relevant equipment:

**Desktop (please complete the following information):**
 - OS:  iOS
 - Browser safari

**Comment by tagyoureit** [comment]
Not sure if this is still an issue, but I may have just fixed something that could have been causing some strange issues.  Either way, I'll close this for now and please re-open if you still have the problem.

Issue possibly fixed as part of: https://github.com/tagyoureit/nodejs-poolController/issues/365

**Comment by Exit2Studios** [comment]
Hi @tagyoureit  and @rstrouse,

I'm sorry to revisit this very old "issue" but I'm having a bit of a hard time getting my head around this behavior.  I have the same Circuit Groups set up and I just don't understand the logic of how it is working.  What is the best way to accomplish the 3 options I have above (spa jets, waterfall, and spa spill)?  As I have it setup now, they can all be on at the same time, which shouldn't be able to happen.  I need to figure out a logical way to only allow for one of those options at a time.  Basically the Aux Pump is on for all three, but the Feature Valves (not my main Intake/Return) change based on mode.

**Comment by tagyoureit** [comment]
Since the initial issue was so long ago, can you upload another replay capture?  

And to clarify... what is the exact problem you are facing?  Are all three circuit groups on at the same time?  Or are all three features on at the same time?

**Comment by tagyoureit** [comment]
Follow these instructions for the [replay capture](https://github.com/tagyoureit/nodejs-poolController/wiki/How-to-capture-all-packets-for-issue-resolution#-dashpanel).  Start the replay with all of your circuit groups off.  Change one, wait 10 seconds, change another one, wait 10 seconds, etc.  Then end the replay and upload it here.

**Comment by Exit2Studios** [comment]
[replay.zip](https://github.com/tagyoureit/nodejs-poolController/files/9075205/replay.zip)

**Comment by tagyoureit** [comment]
The replay only shows me that your comms aren't working and some of the actions were delayed/cancelled because of a cleaner startup delay.  I'll try to replicate your light group issue separately.

I've got a few questions... 
1. I assume your shared body has a spa that can spill over into the pool, yes?
2. Are your spa jets hooked up separately from your regular spillway and filter (to the Aux pump)?
3. What type of pump is your Aux Pump?  Is it a single speed pump?  How is it wired to your electric panel?
4. Are you able to control your VSF pump through this app?
5. How many valves/diverters do you have?  How are they laid out?  Can you send a picture?  (If you want to give an entire overview of your pool in the [My Pool](https://github.com/tagyoureit/nodejs-poolController/discussions/categories/my-pool) section of the discussion forums that would be great.)
6.  Do you have a cleaner?  How is it controlled?

**Comment by tagyoureit** [comment]
Pull the latest.  I found an issues with the circuit group logic.  But also lmk about the answers to my questions above... I'm curious about your pool setup and may have some suggestions.

**Comment by Exit2Studios** [comment]
@rstrouse , you and I had a similar conversation on this on the gitter page a while back (same issue), and I posted some info on my pool there.  However, I've posted an overview in [My Pool #520](https://github.com/tagyoureit/nodejs-poolController/discussions/520) section as well.  

To answer your questions:

1. Yes, my shared body has a spa, but No it does not spill over into the pool.  It spills over into the infinity edge catch basin (which creates some operational challenges)
2. Spa jets (and Scuppers) share the Auxiliary pump and are not connected to the main pump.
3. Aux pump is a Pentair Whisperflo single speed.  It is currently controlled by my Hayward panel, but will be controlled by a 3HP relay once I switch over completely to njsPC
4. I am able to control my VSF from njsPC, but it is not currently hooked up at all (hence the comm issues)
5. I have 4 valves, 2 for standard intake/return and two that control the spa jets and water scuppers.  These also have the added benefit of being able to spill over (completely or small percentage) the spa to keep the negative edge on the spa moving.
8. I have a Maytronics/Pentair Warrior SE (which replaced a Prowler 920, which replaced a pressure side Polaris 280), currently controlled via smart plug over Home Assistant.

As always, thank you for your dedication to this project and patience with people like me :-)

**Comment by tagyoureit** [comment]
There are a few things you should consider when setting up Nixie.  Some of these may not seem to make a difference but will semantically let the app know what's what and be able to control in in the most efficient manner.

1. You should setup your single speed pump to run whenever the waterfall, spa fill or spa jets are on.  (*Pull njsPC and dP and we just changed this over from needing to be a body association).  This eliminates the need for having an aux circuit called Aux Pump and it will also show up as an actual pump.  
![2022-07-10_11-31-52](https://user-images.githubusercontent.com/1646840/178157662-64da66e6-92da-42dc-bab0-4826e0ad901c.png)

You'll also see if I have the circuits in the pump definitions assigned to the pool and spa.  You previously had speed boost +/- there but those are specifically for remote controls and won't work like you are expecting.  You could add additional circuits and set their associated speeds here.

You can also setup the valves as known valve items.  This puts the logic for certain valve functions at the right place instead of just treating them like an off/on switch.  (EG if you want the pump to turn off during valve activation.). Because you still want the spa jets g group to have both diverters active the right way to do that is to have the circuit group. 

![2022-07-10_11-35-29](https://user-images.githubusercontent.com/1646840/178157787-9bcf99bc-34a2-42c7-b331-1c8334937d67.png)

Finally, your groups could then be a bit tidier.  The pump already knows to turn on with the waterfall, spa spill and spa jets so you can leave out the Aux Pump circuit.   
![2022-07-10_11-42-37](https://user-images.githubusercontent.com/1646840/178157864-9dc10c8b-8df3-471b-8a66-f5c900aa0518.png)

**Comment by Exit2Studios** [comment]
I do notice that if I turn off "Waterfall G", the aux valves both turn on, and "Spa Jets G" turns on.  Is this expected behavior?

**Comment by tagyoureit** [comment]
D'oh!  Right... the conditions I posted for Waterfall G and Spa Jets G are completely inverse so at least one will always be on.  Go back to your original circuit group configuration in the very first post in this thread.  Except... don't setup the relay for the pump from the Aux Pump circuit, but create a pump that runs when the Aux Pump circuit is on.  Then it will appear as a pump but give you the same functionality.  

At this point, you can hide the aux pump, feature intake, and feature return 'features' if you want.

![2022-07-11_10-13-53](https://user-images.githubusercontent.com/1646840/178320597-d2f3afdf-aa88-46a3-9b53-fb725288eebe.png)

![2022-07-11_10-18-11](https://user-images.githubusercontent.com/1646840/178321209-b6ddfa97-de95-42d4-85d4-03c86ead232f.png)


![2022-07-11_10-17-03](https://user-images.githubusercontent.com/1646840/178320993-2ee80699-5877-4b2f-a5e9-3773446ab28c.png)

**Comment by Exit2Studios** [comment]
That works much better.  However, when I turn the Waterfall G group off, the Aux Intake and Return Valves turn on.  Same for Spa Spill G, when I turn it off, the Aux Intake valve turns on.

**Comment by Exit2Studios** [comment]
I also have another strange behavior.  When I choose "low speed", the relay for the Aux Pump turns on and off repeatedly.
<img width="624" alt="image" src="https://user-images.githubusercontent.com/16908875/178329290-b25bd37e-72c5-443a-b928-f542d7442085.png">
<img width="630" alt="image" src="https://user-images.githubusercontent.com/16908875/178329345-2e22edcb-a737-4889-b154-cb18b6cd9bc1.png">
<img width="623" alt="image" src="https://user-images.githubusercontent.com/16908875/178329383-8b937a6f-7303-41c4-8a78-3ecdd7bfcb25.png">

**Comment by tagyoureit** [comment]
> I also have another strange behavior. When I choose "low speed", the relay for the Aux Pump turns on and off repeatedly.

I don't see any overlap between Low Speed/High Speed and your Aux1.  You might have something that is still pointing to it somewhere.  You can upload a new replay and I can also take a look.

You should, however, have the "pool" circuit as part of your VSF.  It can be your low speed if you want, but you shouldn't need to turn on the pool and then additionally select a speed.

> That works much better. However, when I turn the Waterfall G group off, the Aux Intake and Return Valves turn on. Same for Spa Spill G, when I turn it off, the Aux Intake valve turns on.

I'm also checking with @rstrouse and looking at the manual regarding the default behavior of circuit groups.  Should turning off the circuit group turn off all the circuits?  Or should it invert the status of each circuit.  Right now, we have it inverting the status of each circuit.

**Comment by Exit2Studios** [comment]
> I don't see any overlap between Low Speed/High Speed and your Aux1. You might have something that is still pointing to it somewhere. You can upload a new replay and I can also take a look.

It looks like a restart fixed this behavior, so not sure what the gremlin was.  Strange for sure.

>You should, however, have the "pool" circuit as part of your VSF. It can be your low speed if you want, but you shouldn't need to turn on the pool and then additionally select a speed.

This makes sense and I will make that change.  Is it appropriate to have the "low speed" defined in the Aux Circuits as I do?

> I'm also checking with @rstrouse and looking at the manual regarding the default behavior of circuit groups. Should turning off the circuit group turn off all the circuits? Or should it invert the status of each circuit. Right now, we have it inverting the status of each circuit.

To my very uneducated mind, it seems like having the option to turn off somehow, either by adding circuit groups as an option or some other way would make sense, but I'll be interested to hear what you both come up with.

Thanks as always!

**Comment by tagyoureit** [comment]
> Is it appropriate to have the "low speed" defined in the Aux Circuits as I do?

No, simply assign the pool circuit as the low speed.

> To my very uneducated mind, it seems like having the option to turn off somehow, either by adding circuit groups as an option or some other way would make sense, but I'll be interested to hear what you both come up with.

This is the worst of all worlds, but if you have an "all off" group and turn it on it will effectively turn off your three circuits (but this group would be on).  

![2022-07-11_16-43-19](https://user-images.githubusercontent.com/1646840/178376839-883449a0-f497-4dc3-b60a-45e9d24d661a.png)

Let me work on making a toggle for either inverting the states or turning off all the circuits.

**Comment by tagyoureit** [comment]
Pull dashpanel and njsPC.  I added an On/Ignore (turn the circuit on when the group turns on; ignore it when it turns off) and Off/Ignore (turn the circuit off when the group turns on; ignore it when it turns off).  Interestingly enough, Intellicenter treats 'ignore' as the On/Ignore behavior above but what you need is the Off/Ignore, hence I added both options explicitly.  I'm treating `ignore` as simply that - ignore the circuit state when either turning the group on or off.  

![2022-07-12_00-21-50](https://user-images.githubusercontent.com/1646840/178432395-59b6f147-2824-4ef4-911f-326c42f6afbd.png)

**Comment by Exit2Studios** [comment]
Brilliant, thank you!

**Comment by rock-crusher** [comment]
So, this is interesting.

I too have noticed odd things in the circuit groups.

One thing I noticed is the pump delay function while valves are in motion does not work in the circuit group if the circuits are not listed in a specific order in the group circuit window.

Why should it make a difference what order you put the circuits in?

<img width="392" alt="delays" src="https://user-images.githubusercontent.com/94593954/179121018-67877a68-1167-438e-a413-35dbdab8af7e.png">

<img width="395" alt="no work" src="https://user-images.githubusercontent.com/94593954/179120813-87719ec3-a368-4c39-b5d3-7302e0c80cb9.png">

<img width="392" alt="works" src="https://user-images.githubusercontent.com/94593954/179120859-23bcd30b-c79c-4ba7-bc2e-4cb8dc583230.png">

**Comment by tagyoureit** [comment]
Just so I don't chase my tail, can you tell me if which circuit functions and valves your circuits are assigned to?

Circuit - Circuit Function - Valve - Valve Assignment
--------------------------
Spa - Spa - Valve C - Spa
Spillway - Spillway - Valve D - Spillway

Or better yet, send another replay so I have your exact setup.  Given your specific scenario, I could envision you setting up your pool any number of ways.

**Comment by rstrouse** [comment]
Actually that spa circuit and the spillway circuit are both specifically impacting Intake and Return valves.  The order in which this is done will determine whether the valve rotation delays will be in effect.  The key for this function is to preserve heat in the spa when switching the valve positions.  Turning the spillway on throws all of that out the window since the return valve is in the diverted position and the intake is not diverted.

If you want to empty the folks out of the spa switch to pool mode when the water temp < 60F with no delays.

If you are cavitating your pump or causing hammer while rotating either the intake or return valves even at full pump speed you should maybe revisit your plumbing.

**Comment by rock-crusher** [comment]
I should have been more specific. In each configuration the spa delay always works as it should, it’s the spillway pump delay that only works when the configuration is set-up as the picture below shows.

I was just more curious than anything as to why it acted this way. In the configuration below, the spillway activates the return valve to the spa all while the pump pauses the 30 second delay.  It does exactly what I expected and wanted it to do in this configuration. I was just confused about when the two are flipped in the configuration (spillway listed first & spa second) the pump delay was omitted during the spillway return valve rotation to the spa. 

As always thanks again for your explanation.

<img width="392" alt="Works" src="https://user-images.githubusercontent.com/94593954/179296921-0c85e593-71f7-481f-b4b6-a2af9ad96290.png">

**Comment by rock-crusher** [comment]
> It is rotating the spillway mode first in the other configuration. 

Actually, it rotates the spillway mode first in either configuration. Just one has the pump delay and the other does not.

>You will also find that when you turn this group on and it is in pool mode it should not delay because the intake valve is already in the resultant position.

As long as the configuration is set as shown in the picture above and you turn this group on when in pool mode it does in fact shutdown the pump for the 30 second delay while the return valve is rotating to spillway mode.

Maybe I’m just not explaining myself correctly, or simply not understanding, or trying to do something it’s not designed to do, although in the above picture configuration it’s doing exactly what I want/need it to do if that makes any sense?

**Comment by tagyoureit** [comment]
I think I know what's going on.  You can only have the spillway activated when the pool is running.   It's not a valid state to have the spa and spillway both on at the same time.  You can test this in Nixie - Turn on the pool and you can toggle the spillway on/off.  Turn on the spa and the spillway is locked out.  

"works as it should" scenario - 
the group turns off the spa, and then pool mode is activated and the spillway is turned on.  

"delay doesn't work" scenario - 
the group is trying to turn on the spillway with the spa on, the command will get rejected.  But the next command will turn off the spa, so the spillway could subsequently be turned on.

Given this logic, anytime your spa is on that means your 'enjoy spa' group is necessarily on.

**Comment by rock-crusher** [comment]
Hi tagyoureit and thanks for responding.

>"works as it should" scenario -
the group turns off the spa, and then pool mode is activated and the spillway is turned on.

That is not exactly how it is set-up (see pic below). The intent was for when the “enjoy spa” is turned on the spillway activates for 1min, or whatever time length I decide to set it for, in this case it’s the 1 min. When activated, the pump is delayed for 30 seconds while the spillway return valve rotates. After the valve completes rotation the pump turns on at 3450 rpm. This will allow the spa to completely fill and also skim whatever leaves/debris happens to be on the surface of the water pushing it over and through the spillway for the skimmer to get later. After the “enjoy spa” circuit group times out (1min) the pump automatically shuts down (30 second delay) and turns on the spa mode which rotates the intake valve to spa, fires up the heater etc. I know, the delays aren’t necessary, but I just like them (I think rstrouse laughs because I always want to implement a delay every time a valve moves…Lol.) 

I’ve used this set-up before and it’s nice especially when children are playing in the spa splashing out lots of water, getting in/out and tracking all sorts of misc. debris in with them. Then, when it’s time for the adults to get in I just simply hit the “enjoy spa” and the water is replenished, the top skimmed off and ready to go.

>"delay doesn't work" scenario -
the group is trying to turn on the spillway with the spa on, the command will get rejected. But the next command will turn off the spa, so the spillway could subsequently be turned on.

The spa is never on, if you look at the same picture again below, you will see that the spa is set to off/on and the spillway set to on/off. 

Like I said before, this is working just fine for me, I was just wondering why the other configuration omitted the delay. 

<img width="392" alt="enjoy spa group" src="https://user-images.githubusercontent.com/94593954/179339619-2639cec5-29b8-46b0-8c08-17a5151bc80e.png">

**Comment by tagyoureit** [comment]
I fixed a place in the code where we run run some of the commands for changing the state of a body even if it was already in that state.  EG when you were turning off the spa but the spa was already off we were ending all of the delays.  Now I am checking to make sure the desired state of the body isn't already the current state before running the logic.  Both of your scenarios should now function the same.

**Comment by rock-crusher** [comment]
Hi tagyoureit… Lol Awesome!

Just tried it out and she works great! No more confusion here, THANKS!!

I really appreciate you guys (tagyoureit/rstrouse) taking the time helping me understand all this madness. 

Cheers!  

<img width="112" alt="beer" src="https://user-images.githubusercontent.com/94593954/179370563-d52725b6-6e63-485e-b6a6-f4d7650e0ca3.png">
