### ISSUE TITLE
Connect via network

### ISSUE THREAD

**Issue by parnic** [tagyoureit/nodejs-poolController#86]
I saw your "wish list" note about wanting to add support for communicating with a system over the network. I've created [node-screenlogic](https://github.com/parnic/node-screenlogic) for this if you'd like to take a look or use it. It currently only supports "read" queries (no way to set heat mode, light colors, etc. just yet) and only a subset of messages, but I plan on expanding it to add more stuff.

**Comment by tagyoureit** [comment]
Fantastic!  I'm really interested in seeing what Configuration information we can get back for more dynamic support of setting up the the right configuration (number of expansion ports, presence of different components, etc).  Also anything about pump status.  And some more.  Am excited to take a look at what you have already.

**Comment by abovesociety** [comment]
Can you guys create a Homebridge plug-in for pentair integration with home kit?

**Comment by tagyoureit** [comment]
> Can you guys create a Homebridge plug-in for pentair integration with home kit?

This should really not belong to this issue... but having said that, and having done some homebridge programming before I can say this would be a great community investment, but I won't be putting hours into this.  You should check out the SmartThings integrations that we have, though.

**Comment by christensonautohome** [comment]
isn't this a plug-in for homebridge?
https://github.com/leftyfl1p/homebridge-poolcontroller

**Comment by tagyoureit** [comment]
Oh, yes. I forgot about that. I don’t remember if he made it compatible with 4.0 or the 4.x-DEV branch, though.

**Comment by dennypage** [comment]
Was this closed because the network connection feature is no longer desirable? Or because the Homebridge issue?

**Comment by tagyoureit** [comment]
This was closed because this app is primarily based on reading the serial port packets and decoding them.  Not everyone has a ScreenLogic.  It would be interesting at some point to read the screenlogic network traffic but it would likely be a heavy lift when you can buy a $7 RS485 adapter and plug it into your system.

While it might be slightly more convenient for those that want to read the network protocol it doesn't but us much in functionality and the effort probably isn't worth it.
